"""Business domain tables: CRM, billing, contracts, support, entitlements.

Hand-written rather than autogenerated: no database was reachable when Phase 2
was built, and `alembic revision --autogenerate` requires one. Once a server is
available, `alembic check` will confirm this migration and the models agree —
that command exists precisely to catch the drift a hand-written migration can
introduce, and running it is a Phase 2 completion task.

Constraint and index names are written out to match the metadata naming
convention in ``custops.db.base``. Note that the convention templates *check*
constraint names as ``ck_<table>_<given name>``, which is why the models declare
short names like ``seats_positive``.

Revision ID: 0003_domain_tables
Revises: 0002_foundation_tables
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003_domain_tables"
down_revision: str | None = "0002_foundation_tables"
branch_labels: str | None = None
depends_on: str | None = None

MONEY = sa.Numeric(12, 2)
PERCENT = sa.Numeric(5, 2)


def _timestamps() -> tuple[sa.Column[sa.DateTime], sa.Column[sa.DateTime]]:
    return (
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )


def upgrade() -> None:
    # --- CRM ---------------------------------------------------------------
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_ref", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("industry", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_customers"),
        sa.UniqueConstraint("external_ref", name="uq_customers_external_ref"),
    )
    op.create_index("ix_customers_name", "customers", ["name"])
    op.create_index("ix_customers_status", "customers", ["status"])

    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("billing_email", sa.String(length=320), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        # The CRM's own cached copy of the plan — one of the three records the
        # Validator cross-checks (BUILD_SPEC §14).
        sa.Column("current_plan_code", sa.String(length=32), nullable=True),
        sa.Column("lifecycle_stage", sa.String(length=32), nullable=False),
        sa.Column("last_plan_change_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name="fk_accounts_customer_id_customers",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_accounts"),
    )
    op.create_index("ix_accounts_customer_id", "accounts", ["customer_id"])
    op.create_index("ix_accounts_status", "accounts", ["status"])

    op.create_table(
        "contacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        *_timestamps(),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_contacts_account_id_accounts",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_contacts"),
    )
    op.create_index("ix_contacts_account_id", "contacts", ["account_id"])
    op.create_index("ix_contacts_email", "contacts", ["email"])

    # --- Billing -----------------------------------------------------------
    op.create_table(
        "plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        # Ordering, so "is this an upgrade?" is a comparison, not a lookup table.
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("monthly_price", MONEY, nullable=False),
        sa.Column("annual_price", MONEY, nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        *_timestamps(),
        sa.CheckConstraint("monthly_price >= 0", name="ck_plans_monthly_price_non_negative"),
        sa.CheckConstraint("annual_price >= 0", name="ck_plans_annual_price_non_negative"),
        sa.PrimaryKeyConstraint("id", name="pk_plans"),
        sa.UniqueConstraint("code", name="uq_plans_code"),
    )

    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("billing_cycle", sa.String(length=16), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        *_timestamps(),
        sa.CheckConstraint("seats >= 1", name="ck_subscriptions_seats_positive"),
        sa.CheckConstraint(
            "current_period_end > current_period_start",
            name="ck_subscriptions_period_ordered",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_subscriptions_account_id_accounts",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], name="fk_subscriptions_plan_id_plans"),
        sa.PrimaryKeyConstraint("id", name="pk_subscriptions"),
    )
    op.create_index("ix_subscriptions_account_id", "subscriptions", ["account_id"])
    op.create_index("ix_subscriptions_plan_id", "subscriptions", ["plan_id"])
    op.create_index("ix_subscriptions_status", "subscriptions", ["status"])

    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount_due", MONEY, nullable=False),
        sa.Column("amount_paid", MONEY, nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        *_timestamps(),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_invoices_account_id_accounts",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name="fk_invoices_subscription_id_subscriptions",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_invoices"),
        sa.UniqueConstraint("number", name="uq_invoices_number"),
    )
    op.create_index("ix_invoices_account_id", "invoices", ["account_id"])
    op.create_index("ix_invoices_subscription_id", "invoices", ["subscription_id"])
    op.create_index("ix_invoices_status", "invoices", ["status"])

    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("amount", MONEY, nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name="fk_payments_invoice_id_invoices",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_payments"),
    )
    op.create_index("ix_payments_invoice_id", "payments", ["invoice_id"])
    op.create_index("ix_payments_status", "payments", ["status"])

    op.create_table(
        "discounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("percent_off", PERCENT, nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        # Nullable and SET NULL: a discount's approval history must survive the
        # approver's account being removed.
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            "percent_off >= 0 AND percent_off <= 100",
            name="ck_discounts_percent_off_in_range",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_discounts_account_id_accounts",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name="fk_discounts_approved_by_user_id_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_discounts"),
    )
    op.create_index("ix_discounts_account_id", "discounts", ["account_id"])

    # --- Contracts and policies -------------------------------------------
    op.create_table(
        "contracts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("contract_number", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("minimum_term_months", sa.Integer(), nullable=False),
        sa.Column("notice_period_days", sa.Integer(), nullable=False),
        # Structured and machine-checkable; read by the eligibility rule.
        sa.Column("upgrade_restriction", sa.String(length=32), nullable=False),
        sa.Column("price_increase_cap_percent", PERCENT, nullable=True),
        # Prose; retrieved as evidence, never the authority for a decision.
        sa.Column("document_body", sa.Text(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint("ends_at > starts_at", name="ck_contracts_term_ordered"),
        sa.CheckConstraint(
            "minimum_term_months >= 0", name="ck_contracts_minimum_term_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_contracts_account_id_accounts",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_contracts"),
        sa.UniqueConstraint("contract_number", name="uq_contracts_contract_number"),
    )
    op.create_index("ix_contracts_account_id", "contracts", ["account_id"])
    op.create_index("ix_contracts_status", "contracts", ["status"])

    op.create_table(
        "policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.CheckConstraint("version >= 1", name="ck_policies_version_positive"),
        sa.PrimaryKeyConstraint("id", name="pk_policies"),
    )
    op.create_index("ix_policies_code", "policies", ["code"])
    op.create_index("ix_policies_category", "policies", ["category"])

    # --- Support -----------------------------------------------------------
    op.create_table(
        "support_tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("satisfaction_score", sa.Integer(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            "satisfaction_score IS NULL OR (satisfaction_score BETWEEN 1 AND 5)",
            name="ck_support_tickets_satisfaction_in_range",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_support_tickets_account_id_accounts",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_support_tickets"),
        sa.UniqueConstraint("reference", name="uq_support_tickets_reference"),
    )
    op.create_index("ix_support_tickets_account_id", "support_tickets", ["account_id"])
    op.create_index("ix_support_tickets_category", "support_tickets", ["category"])
    op.create_index("ix_support_tickets_status", "support_tickets", ["status"])
    op.create_index("ix_support_tickets_priority", "support_tickets", ["priority"])

    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("author_type", sa.String(length=16), nullable=False),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        # No updated_at: a message is not edited, it is followed by another.
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["support_tickets.id"],
            name="fk_conversations_ticket_id_support_tickets",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_conversations"),
    )
    op.create_index("ix_conversations_ticket_id", "conversations", ["ticket_id"])

    # --- Entitlements (mirror of the legacy portal, D8) --------------------
    op.create_table(
        "entitlements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("tier", sa.String(length=32), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        # Without this, a stale mirror is indistinguishable from a fresh one.
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name="fk_entitlements_account_id_accounts",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_entitlements"),
        sa.UniqueConstraint("account_id", name="uq_entitlements_account_id"),
    )
    op.create_index("ix_entitlements_account_id", "entitlements", ["account_id"])


def downgrade() -> None:
    # Reverse dependency order.
    op.drop_table("entitlements")
    op.drop_table("conversations")
    op.drop_table("support_tickets")
    op.drop_table("policies")
    op.drop_table("contracts")
    op.drop_table("discounts")
    op.drop_table("payments")
    op.drop_table("invoices")
    op.drop_table("subscriptions")
    op.drop_table("plans")
    op.drop_table("contacts")
    op.drop_table("accounts")
    op.drop_table("customers")
